from __future__ import annotations

from kva_engine.schemas import VoiceActingPlan


PRESETS: dict[str, VoiceActingPlan] = {
    "calm_narrator": VoiceActingPlan(
        role="calm_narrator",
        emotion="neutral_confident",
        identity_strength=0.82,
        role_strength=0.45,
        pitch_shift=-1.0,
        pitch_variance=0.82,
        speed=0.92,
        breathiness=0.12,
        articulation_strength=0.78,
        pause_scale=1.1,
        ending_style="low_falling",
        formality="polite",
    ),
    "documentary": VoiceActingPlan(
        role="documentary",
        emotion="quiet_awe",
        identity_strength=0.78,
        role_strength=0.58,
        pitch_shift=-2.0,
        pitch_variance=0.72,
        speed=0.86,
        breathiness=0.18,
        articulation_strength=0.74,
        pause_scale=1.25,
        ending_style="deep_falling",
        formality="polite",
    ),
    "news_anchor": VoiceActingPlan(
        role="news_anchor",
        emotion="controlled_clear",
        identity_strength=0.74,
        role_strength=0.62,
        pitch_shift=0.0,
        pitch_variance=0.55,
        speed=1.0,
        breathiness=0.04,
        articulation_strength=0.92,
        pause_scale=0.95,
        ending_style="firm_falling",
        formality="formal",
    ),
    "bright_teacher": VoiceActingPlan(
        role="bright_teacher",
        emotion="warm_encouraging",
        identity_strength=0.8,
        role_strength=0.5,
        pitch_shift=1.5,
        pitch_variance=0.9,
        speed=0.98,
        breathiness=0.1,
        articulation_strength=0.82,
        pause_scale=1.0,
        ending_style="friendly_falling",
        formality="polite",
    ),
    "old_storyteller": VoiceActingPlan(
        role="old_storyteller",
        emotion="warm_regret",
        identity_strength=0.68,
        role_strength=0.75,
        pitch_shift=-4.0,
        pitch_variance=0.65,
        speed=0.78,
        breathiness=0.45,
        articulation_strength=0.64,
        pause_scale=1.45,
        ending_style="low_falling",
        formality="plain",
    ),
    "villain_low": VoiceActingPlan(
        role="villain_low",
        emotion="restrained_threat",
        identity_strength=0.62,
        role_strength=0.82,
        pitch_shift=-5.0,
        pitch_variance=0.5,
        speed=0.74,
        breathiness=0.22,
        articulation_strength=0.7,
        pause_scale=1.35,
        ending_style="held_low",
        formality="plain",
    ),
    "childlike_fast": VoiceActingPlan(
        role="childlike_fast",
        emotion="curious_bright",
        identity_strength=0.52,
        role_strength=0.9,
        pitch_shift=5.0,
        pitch_variance=1.25,
        speed=1.16,
        breathiness=0.08,
        articulation_strength=0.76,
        pause_scale=0.82,
        ending_style="light_rising",
        formality="plain",
    ),
    "ai_assistant": VoiceActingPlan(
        role="ai_assistant",
        emotion="kind_precise",
        identity_strength=0.76,
        role_strength=0.5,
        pitch_shift=0.5,
        pitch_variance=0.62,
        speed=0.96,
        breathiness=0.05,
        articulation_strength=0.88,
        pause_scale=1.02,
        ending_style="clean_falling",
        formality="polite",
    ),
    "twentyfirst_prince_lead": VoiceActingPlan(
        role="twentyfirst_prince_lead",
        emotion="restrained_modern_royal_confidence",
        identity_strength=0.36,
        role_strength=0.92,
        pitch_shift=-2.5,
        pitch_variance=0.64,
        speed=0.88,
        breathiness=0.14,
        articulation_strength=0.84,
        pause_scale=1.18,
        ending_style="composed_low_falling",
        formality="polite",
    ),
    "twentyfirst_grand_lady_lead": VoiceActingPlan(
        role="twentyfirst_grand_lady_lead",
        emotion="warm_dignified_modern_grace",
        identity_strength=0.24,
        role_strength=0.96,
        pitch_shift=4.2,
        pitch_variance=0.86,
        speed=0.94,
        breathiness=0.18,
        articulation_strength=0.86,
        pause_scale=1.08,
        ending_style="graceful_soft_falling",
        formality="polite",
    ),
    "wolf_growl": VoiceActingPlan(
        role="wolf_growl",
        emotion="low_animal_warning",
        identity_strength=0.45,
        role_strength=0.94,
        pitch_shift=-4.5,
        pitch_variance=0.48,
        speed=0.82,
        breathiness=0.35,
        articulation_strength=0.55,
        pause_scale=1.28,
        ending_style="rough_low_falling",
        formality="plain",
    ),
    "wolf_growl_clear": VoiceActingPlan(
        role="wolf_growl_clear",
        emotion="clear_low_warning",
        identity_strength=0.52,
        role_strength=0.82,
        pitch_shift=-3.5,
        pitch_variance=0.58,
        speed=0.88,
        breathiness=0.25,
        articulation_strength=0.66,
        pause_scale=1.18,
        ending_style="low_falling",
        formality="plain",
    ),
    "wolf_growl_heavy": VoiceActingPlan(
        role="wolf_growl_heavy",
        emotion="rough_animal_threat",
        identity_strength=0.35,
        role_strength=0.98,
        pitch_shift=-6.0,
        pitch_variance=0.42,
        speed=0.76,
        breathiness=0.48,
        articulation_strength=0.42,
        pause_scale=1.4,
        ending_style="rough_low_falling",
        formality="plain",
    ),
    "monster_deep": VoiceActingPlan(
        role="monster_deep",
        emotion="heavy_menace",
        identity_strength=0.38,
        role_strength=0.97,
        pitch_shift=-7.0,
        pitch_variance=0.42,
        speed=0.72,
        breathiness=0.5,
        articulation_strength=0.48,
        pause_scale=1.45,
        ending_style="rumbling_low",
        formality="plain",
    ),
    "monster_deep_clear": VoiceActingPlan(
        role="monster_deep_clear",
        emotion="clear_heavy_menace",
        identity_strength=0.44,
        role_strength=0.88,
        pitch_shift=-5.0,
        pitch_variance=0.5,
        speed=0.8,
        breathiness=0.35,
        articulation_strength=0.58,
        pause_scale=1.28,
        ending_style="heavy_low",
        formality="plain",
    ),
    "monster_deep_fx": VoiceActingPlan(
        role="monster_deep_fx",
        emotion="distorted_heavy_menace",
        identity_strength=0.28,
        role_strength=0.99,
        pitch_shift=-8.0,
        pitch_variance=0.35,
        speed=0.66,
        breathiness=0.62,
        articulation_strength=0.34,
        pause_scale=1.55,
        ending_style="rumbling_low",
        formality="plain",
    ),
    "dinosaur_giant": VoiceActingPlan(
        role="dinosaur_giant",
        emotion="ancient_giant",
        identity_strength=0.32,
        role_strength=0.99,
        pitch_shift=-8.0,
        pitch_variance=0.36,
        speed=0.72,
        breathiness=0.55,
        articulation_strength=0.42,
        pause_scale=1.65,
        ending_style="giant_roar_fall",
        formality="plain",
    ),
    "dinosaur_giant_clear": VoiceActingPlan(
        role="dinosaur_giant_clear",
        emotion="clear_ancient_giant",
        identity_strength=0.38,
        role_strength=0.9,
        pitch_shift=-6.5,
        pitch_variance=0.44,
        speed=0.78,
        breathiness=0.42,
        articulation_strength=0.52,
        pause_scale=1.35,
        ending_style="giant_low_fall",
        formality="plain",
    ),
    "dinosaur_giant_roar": VoiceActingPlan(
        role="dinosaur_giant_roar",
        emotion="massive_roar",
        identity_strength=0.22,
        role_strength=1.0,
        pitch_shift=-11.0,
        pitch_variance=0.3,
        speed=0.62,
        breathiness=0.72,
        articulation_strength=0.25,
        pause_scale=1.8,
        ending_style="giant_roar_fall",
        formality="plain",
    ),
    "child_bright": VoiceActingPlan(
        role="child_bright",
        emotion="bright_child",
        identity_strength=0.42,
        role_strength=0.92,
        pitch_shift=6.0,
        pitch_variance=1.35,
        speed=1.12,
        breathiness=0.08,
        articulation_strength=0.72,
        pause_scale=0.82,
        ending_style="light_rising",
        formality="plain",
    ),
}


def get_preset(role: str) -> VoiceActingPlan:
    try:
        return PRESETS[role]
    except KeyError as exc:
        available = ", ".join(sorted(PRESETS))
        raise ValueError(f"Unknown role: {role}. Available roles: {available}") from exc
